### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by adsaleksei** [konichar/parsesig#12]
Hi,

i'm trying to install local and after the commands it doesn't generate or is missing  the telethon_access.py file.
Would you help me?
ubuntu 18.04
Python 3.6.9
[parsesig.txt](https://github.com/konichar/parsesig/files/6322841/parsesig.txt)
Thanks!

**Comment by adsaleksei** [comment]
2021-04-18T06:32:19.987429+00:00 app[api]: Release v45 created by user XXX
2021-04-18T06:32:21.056201+00:00 heroku[worker.1]: State changed from crashed to starting
2021-04-18T06:32:26.620161+00:00 heroku[worker.1]: Starting process with command `python3 main.py`
2021-04-18T06:32:27.522708+00:00 heroku[worker.1]: State changed from starting to up
2021-04-18T06:32:29.000000+00:00 app[api]: Build succeeded
2021-04-18T06:32:33.042101+00:00 app[worker.1]: Please enter your phone (or bot token): Traceback (most recent call last):
2021-04-18T06:32:33.042187+00:00 app[worker.1]: File "/app/main.py", line 61, in <module>
2021-04-18T06:32:33.042547+00:00 app[worker.1]: client.start()
2021-04-18T06:32:33.042585+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.9/site-packages/telethon/client/auth.py", line 133, in start
2021-04-18T06:32:33.042895+00:00 app[worker.1]: else self.loop.run_until_complete(coro)
2021-04-18T06:32:33.042919+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
2021-04-18T06:32:33.043489+00:00 app[worker.1]: return future.result()
2021-04-18T06:32:33.043518+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.9/site-packages/telethon/client/auth.py", line 170, in _start
2021-04-18T06:32:33.043953+00:00 app[worker.1]: value = phone()
2021-04-18T06:32:33.043981+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.9/site-packages/telethon/client/auth.py", line 21, in <lambda>
2021-04-18T06:32:33.044286+00:00 app[worker.1]: phone: typing.Callable[[], str] = lambda: input('Please enter your phone (or bot token): '),
2021-04-18T06:32:33.044383+00:00 app[worker.1]: EOFError: EOF when reading a line
2021-04-18T06:32:33.267647+00:00 heroku[worker.1]: Process exited with status 1
2021-04-18T06:32:33.372326+00:00 heroku[worker.1]: State changed from up to crashed
